# -*- coding: utf-8 -*-
"""pdss 2024 04/07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XsYtfXEASJjbVKAs7esf2NVn5MwpddY
"""

# Ordenando uma letras, numero e nomes
lista_letras = ['H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']
lista_numeros = [8, 4, 3, 5, 1, 2, 7, 6]
lista_nomes = ["Xavier", "Erick", "Logan", "Jean"]
lista_letras.sort()
lista_numeros.sort()
lista_nomes.sort()
print("Ordenação das letras do alfabeto", lista_letras)
print("Ordenação dos números", lista_numeros)
print("Ordenação dos nomes", lista_nomes)

# Ordenando uma lista não ordenada
lista_letras.sort(reverse=True)
lista_numeros.sort(reverse=True)
listas_nomes.sort(reverse=True)

# Ordenando uma lista não ordenada de forma invertida
print("Ordenação Inversa das Letras do alfabeto", lista_letras)
print("Ordenação Inversa do números", lista_numeros)
print("Ordenação Inversa dos Nomes", lista_nomes)

# Retornando uma lista não ordenada
datas = [1951, 1949, 1813, 1605]
datas_ordenadas = sorted(datas)
print("Datas Não ordenadas", datas)
print("Datas ordenadas", datas_ordenadas)
funcionarios = ["Diana", "Bruno", "Carlos", "Alice", "João", "Evertor"]
numero_registro = [56, 34, 78, 13, 518, 23, 12]
clientes = ["Eva", "Felipe", "Gustavo", "Helena", "Hilsson", "Adalberto"]
saldo_bancario = [2000, -1580, 248, 0, 850, -1900, -350, 528]
ano_nascimento = [1990, 2012, 2004, 1987, 1988, 2003, 2000]
     "Atendimento ao Cliente",
     "Gerenciamento de Projeto",
     "Desenvolvimento de Software",
     "Finanças e Contabilidade",
     "Suporte Técnico"

     def ordenar_lista(lista):
    return sorted(lista)

# Exemplo de uso
minha_lista = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
lista_ordenada = ordenar_lista(minha_lista)
print(lista_ordenada)

def ordenar_lista_inversa(lista):
    return sorted(lista, reverse=True)

# Exemplo de uso
minha_lista = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
lista_ordenada_inversa = ordenar_lista_inversa(minha_lista)
print(lista_ordenada_inversa)